'use client';

import type {
  AiTagSuggestionId,
  AiTagSuggestionWithTag,
  RecipeVersionId,
} from '@commontable/types';
import { Box, Button, Chip, Stack, Typography } from '@mui/material';
import { useState } from 'react';

export interface AiSuggestedTagsListProps {
  /** Pending AI tag suggestions */
  suggestions: AiTagSuggestionWithTag[];
  /** Recipe version ID */
  recipeVersionId: RecipeVersionId;
  /** Callback when user accepts a suggestion */
  onAccept: (suggestionId: AiTagSuggestionId) => Promise<void>;
  /** Callback when user rejects a suggestion */
  onReject: (suggestionId: AiTagSuggestionId) => Promise<void>;
  /** Callback when user accepts all suggestions */
  onAcceptAll: () => Promise<void>;
}

/**
 * Display AI-suggested tags with accept/reject actions
 *
 * Shows pending tag suggestions generated by the AI batch system.
 * Users can accept individual suggestions (click chip) or reject them (click X).
 * "Accept All" button is shown when there are 2+ suggestions.
 *
 * Design System Compliance:
 * - Material UI components only (Box, Stack, Chip, Button, Typography)
 * - Typography variants: h6 (section header), body2 (description)
 * - Button variant: outlined (secondary action)
 * - Spacing: 8px base grid
 * - No custom colors (theme palette only)
 * - Calm, neutral tone (no emojis)
 */
export function AiSuggestedTagsList({
  suggestions,
  recipeVersionId: _recipeVersionId,
  onAccept,
  onReject,
  onAcceptAll,
}: AiSuggestedTagsListProps) {
  const [loading, setLoading] = useState<AiTagSuggestionId | null>(null);
  const [loadingAll, setLoadingAll] = useState(false);

  const handleAccept = async (suggestionId: AiTagSuggestionId) => {
    setLoading(suggestionId);
    try {
      await onAccept(suggestionId);
    } finally {
      setLoading(null);
    }
  };

  const handleReject = async (suggestionId: AiTagSuggestionId) => {
    setLoading(suggestionId);
    try {
      await onReject(suggestionId);
    } finally {
      setLoading(null);
    }
  };

  const handleAcceptAll = async () => {
    setLoadingAll(true);
    try {
      await onAcceptAll();
    } finally {
      setLoadingAll(false);
    }
  };

  if (suggestions.length === 0) {
    return null;
  }

  return (
    <Box>
      <Typography variant="h6">AI Suggested Tags</Typography>
      <Typography variant="body2" color="text.secondary">
        These tags were suggested based on the recipe content
      </Typography>

      <Stack direction="row" spacing={1} sx={{ mt: 2, flexWrap: 'wrap', gap: 1 }}>
        {suggestions.map((suggestion) => (
          <Chip
            key={suggestion.id}
            label={suggestion.tag.name}
            onClick={() => handleAccept(suggestion.id)}
            onDelete={() => handleReject(suggestion.id)}
            color="primary"
            variant="outlined"
            disabled={loading !== null || loadingAll}
            aria-label={`Accept ${suggestion.tag.name}`}
          />
        ))}
      </Stack>

      {suggestions.length > 1 && (
        <Button
          onClick={handleAcceptAll}
          variant="outlined"
          sx={{ mt: 2 }}
          disabled={loading !== null || loadingAll}
          aria-label="Accept all suggestions"
        >
          Accept All
        </Button>
      )}
    </Box>
  );
}
